### ISSUE TITLE
Can we rotate by deg or rad for a layer ?

### ISSUE THREAD

**Issue by phucsang0spt** [clabe45/vidar#105]

**Comment by clabe45** [comment]
Yeah, you can rotate using [vd.effect.Transform](https://calebsacks.me/vidar/docs/api/modules/effect.transform.html).

Looks like some info got left out when that page in the docs was generated, but here's an (untested) example:
```ts
layer.addEffect(
  new vd.effect.Transform(
    new vd.effect.Transform.Matrix().rotate(radians)
  )
)
```

Beware that this does not affect the layer's bounds. You'll want the layer's bounds to match the movie, and crop the content so it's rendered on a part of the layer. This way, the layer won't get cropped when it's rotated. Hopefully in the future we can make this more user-friendly. Perhaps every layer's internal canvas should match the movie's dimensions, but its content is only rendered on the user-defined bounds (`x`, `y`, `width`, `height`).

**Comment by phucsang0spt** [comment]
> Yeah, you can rotate using [vd.effect.Transform](https://calebsacks.me/vidar/docs/api/modules/effect.transform.html).
> 
> Looks like some info got left out when that page in the docs was generated, but here's an (untested) example:
> 
> ```ts
> layer.addEffect(
>   new vd.effect.Transform(
>     new vd.effect.Transform.Matrix().rotate(radians)
>   )
> )
> ```
> 
> Beware that this does not affect the layer's bounds. You'll want the layer's bounds to match the movie, and crop the content so it's rendered on a part of the layer. This way, the layer won't get cropped when it's rotated. Hopefully in the future we can make this more user-friendly. Perhaps every layer's internal canvas should match the movie's dimensions, but its content is only rendered on the user-defined bounds (`x`, `y`, `width`, `height`).

tks 👍

**Comment by clabe45** [comment]
I'm closing this. Feel free to re-open it if this did not work
