### ISSUE TITLE
How to record in high quality?

### ISSUE THREAD

**Issue by Inaztm** [clabe45/vidar#110]
Hi. My movie canvas size is w = 176.625, h = 314, but I want to record in 720p or 1080p.
How to implement it, any idea?

**Comment by Inaztm** [comment]
> Hi, you can set the width and height properties on the canvas or the movie. Both update the canvas's size.

I did it, but there are lags and the video skips frames, I will try on nodejs and workers

**Comment by clabe45** [comment]
I'm closing this for now
