### ISSUE TITLE
Recording doesn't capture the sound from a video in FF

### ISSUE THREAD

**Issue by clabe45** [clabe45/vidar#21]
When *examples/introduction/export.html* is run in firefox, the video layer has no sound (even though the audio layer does).

**Steps to reproduce:**
1. Clone
2. Run `npm run assets && npm start` to start the dev server
3. Open __localhost:8080/examples/introduction/export.html__ in firefox
4. The video segment of the exported movie (with Big Bunny Buck) should contain audio, but it doesn't.

**Comment by moumini-creator** [comment]
Hello, I try to fix it, if you agree ?

**Comment by clabe45** [comment]
Thank you @moumini-creator! You can look at [`Movie#record`](https://github.com/clabe45/vidar/blob/master/src/movie.js#L184) for reference. Let me know if you have any questions!

**Comment by moumini-creator** [comment]
I was able to observe that there were only a few seconds of the video that was being played is this on purpose?

**Comment by clabe45** [comment]
Yeah, that's intentional. The whole movie should be 9 seconds long.

**Comment by moumini-creator** [comment]
So where's the code that controls the cutting of the video? Please. Or I don't quite understand what's going on, in which case please enlighten me on how it works.

**Comment by clabe45** [comment]
The code for the example is located in **examples/introduction/export.html**, if that's what you mean. 

`Movie#record` is the method that renders the video to a file, so that's where the problem should be. It uses the native media recorder API to accumulate the image and audio data for each frame and convert it into one blob at the end. I wonder if changing the blob type in [line 238](https://github.com/clabe45/vidar/blob/master/src/movie.js#L238) would fix it.

On a side note, you have probably run into the issue that the examples are not allowed to play (because of the browsers' autoplay policies). I am working on changing the examples so you have to click to start the movie. In the meantime, you should be able to prevent this behavior in your browser settings.

**Comment by clabe45** [comment]
@moumini-creator Hi, did that fix work? If not, feel free to comment any questions!

**Comment by clabe45** [comment]
This is no longer an issue, I suppose it was fixed in v0.7
