### ISSUE TITLE
MediaWidth & MediaHeight no effect

### ISSUE THREAD

**Issue by zernonia** [clabe45/vidar#33]
Hi, I'm not sure why the media width and height cannot be edited. I've tried the following way, but still unable to change the size of the video on the canvas. 

```
movie
        .addLayer(new vd.layer.Video(0, video, {mediaWidth : cv.width, mediaHeight : cv.height}))
```

or 

```
movie
        .addLayer(new vd.layer.Video(0, video, {mediaWidth : 1280, mediaHeight : 720}))
```

**Comment by clabe45** [comment]
Hello, I just fixed it in the master branch. Until the next release, you could use the `width` option as a workaround. But that affects the whole layer, not just the video on the layer.
