### ISSUE TITLE
Exporting is broken

### ISSUE THREAD

**Issue by saltukkos** [clabe45/vidar#38]
It seems that video exporting doesn't work except the case when you disable audio with options `{audio:false}`.
I investigated that problem is related to `this.actx.createMediaStreamDestination()`, it seems like there is silence in it in any case, also in case there is audio\video layer, and as you wrote, `Chrome doesn't record silence`, so, empty blob is produced. Workaround that I found is to pre-create MediaStreamDestination in Movie constructor and use it when attaching the media like this
```
      this._source = movie.actx.createMediaElementSource(this.media)
      this.source.connect(movie.actxdst) // <--- precreated actx.createMediaStreamDestination()
      this.source.connect(movie.actx.destination)
```
It seems working, but I'm not sure this is legal.
P.S. I also had to change the example to start exporting on user click, not on window loading to make it work stable, but it's a known issue as I understood. 
P.P.S. I was able to reproduce this bug on `Edge`/`Chrome`/`Yandex Browser`/`Opera on Android`. With this workaround exporting seems to work in all that browsers

**Comment by clabe45** [comment]
Hello, thanks for such a detailed write-up! I have been too busy to work on this project lately, but if you want to submit a pull request, I would be more than happy to merge it!

**Comment by eboujlal** [comment]
Can you please do a pull request so can CLABE add yours to the main code ?

**Comment by clabe45** [comment]
@saltukkos What error or problem did you receive, and what did you expect? Can you also please provide some sample code that causes the problem?

**Comment by saltukkos** [comment]
@clabe45 I just tried to run the example with recording. (As I can remember, it's https://github.com/clabe45/vidar/blob/master/examples/introduction/export.html)
In any browser I tried (Chrome, new Edge, Yandex Browser, Opera on Android), the demo didn't work. Player didn't show any video after recording. After some investigation I found, that it would record something if I disable audio by passing `{audio:false}` (of course audio would not be recorded). After deeper investigation I found that empty blob was produced because of absence  of sound in the recorder in any case. The workaround I found is described in the issue (connect the `source` to the result of `actx.createMediaStreamDestination()`), but I'm not sure it's the valid way to go, so, I don't want to make a pull request.

**Comment by clabe45** [comment]
Okay, thank you. I had to create a solution that was a bit more complex, because the audio node graph had to remain intact when we both start and stop recording. This involved spying on `connect` and `disconnect` in the media layer class (as can be seen in acefaad).
