### ISSUE TITLE
Export video to mp4

### ISSUE THREAD

**Issue by eboujlal** [clabe45/vidar#39]
Hello, i tried to export the video to mp4 but i couldnt, is there any way to do that ?

**Comment by clabe45** [comment]
Hello, @eboujlal! I believe you can download the blob, setting the filename to something ending in *.mp4*. Please let me know if that doesn't work.

Although I suspect this will work, really we should add an option for the mimetype in `record` and replace `'video/webm'` with the value provided by the user in [line 222 in movie.js](https://github.com/clabe45/vidar/blob/master/src/movie.js#L222).

I have been too busy to work on this project recently, but PRs are welcome! Please let me know if you have any further questions!

**Comment by eboujlal** [comment]
Can you please add an example how to export video to mp4
thank you

**Comment by clabe45** [comment]
There is one! Check out [examples/introduction/export](https://github.com/clabe45/vidar/blob/master/examples/introduction/export.html). Also, see [the docs for `Movie.record`](https://clabe45.github.io/vidar/docs/api/module-movie.Movie.html#record).
