### ISSUE TITLE
Pixelized objects

### ISSUE THREAD

**Issue by eboujlal** [clabe45/vidar#40]
Hello, when i try to add objects to a layer like a text, it become pixelized, also when i add an image with a width and height lower than the width and the height of the canvas, the canvas dont show the full image, otherwise if i add a bigger image, canvas crop it.

**Comment by clabe45** [comment]
Hello, what you mean by adding objects to a layer like text? Can you provide the code and say what you expected it to look like and what it really looked like?

WRT to the canvas size, a movie is not supposed to resize to fit its layers, but you can set its `width` and `height` to match the image. Please let me know if you have any other questions!

**Comment by eboujlal** [comment]
Hello, its my bad i set width and height of canvas from CSS, but i should set width and height from JAVASCRIPT.
