### ISSUE TITLE
Can't resize an image

### ISSUE THREAD

**Issue by eboujlal** [clabe45/vidar#43]
Hello, after many tries, i figured out, that we can't resize a picture, for example if the canvas is 600x600 and picture is 1024x1024, if we loaded the picture without any options, it will cropped automatically, only a part of the image will be shown. and if we set the original height and the original width in height and width options the image will load correctly but will not fit the canvas, i tried to resize the image inside canvas but nothing is working.

`video.addLayer(new vd.layer.Image(
                        0,
                        5,
                        document.getElementById('img'),
                        {
                            x:15,
                            y:15,
                            width :1024,
                            height :1024,
                        }
                    ));`

Thank you.

**Comment by eboujlal** [comment]
Hello, i managed to find a solution, here is the code
`video.addLayer(new vd.layer.Image(
                        0,
                        5,
                        document.getElementById('img'),
                        {
                            x:0,
                            y:0,
                            width :image.small_width,
                            height :image.small_height,
                            clipWidth:object.original_width,
                            clipHeight:object.original_height
                        }
                    ));`

**Comment by clabe45** [comment]
Thank you, this was definitely a bug. I fixed it in b036d4cb5dca10c3762f0c86cc3645caf5582613. A new version will be released to npm pretty soon.
