### ISSUE TITLE
Image get cropped after applying rotation on it

### ISSUE THREAD

**Issue by eboujlal** [clabe45/vidar#46]
Hello,
There is an issue when we rotate an image, the image get cropped.

When we apply [Matrix#rotate(a)](https://clabe45.github.io/vidar/docs/api/module-effect.Transform.html#.Matrix#rotate) on an image, the image get cropped, is there any solution so we keep showing all of the image while rotating it ?

**Comment by clabe45** [comment]
Hello! Oh, this is because I removed the `imageWidth` and `imageHeight` options in 7ff3d3ec492585b137eeeaf0cdbb9943702a3516. I will re-add them!

**Comment by eboujlal** [comment]
hello is there any solution ?

**Comment by eboujlal** [comment]
hello, i need your help in solving this issue.

**Comment by clabe45** [comment]
Have you tried it with the master branch? I believe it should be fixed.

i.e.
```html
<script src="https://raw.githubusercontent.com/clabe45/vidar/master/dist/vidar-iife.js"></script>
```

Please let me know if the bug is still there.

**Comment by clabe45** [comment]
My bad, I thought I pushed it but got sidetracked and never finished it. I'll work on that now!

**Comment by eboujlal** [comment]
Thank you so much, I create an open source video editing webapp based on Vidar, so i am trying to implement all of the features.

**Comment by eboujlal** [comment]
hello any update ?

**Comment by clabe45** [comment]
I reverted the commit on my local repo, but there were some issues with the code that I brought back that require some major refactoring. It will probably be a few more days until I finish this refactoring.
