### ISSUE TITLE
Examples missing assets folder

### ISSUE THREAD

**Issue by sebastianmacias** [clabe45/vidar#50]
I'm unable to test some of the examples because files such as:

```
/examples/assets/lake.jpg 
/examples/assets/desert.mp4
```
Are missing. Can they be included in the source?

Thanks

**Comment by clabe45** [comment]
I need to update the readme, but run `npm run assets` to download these files. If this results in a commit added to your working branch, please remove the commit and tell me that this happened. The assets will still be in your working directory, as they are gitignored. The unwanted commit is currently an issue I am investigating.
