### ISSUE TITLE
Use currentTime in val()

### ISSUE THREAD

**Issue by clabe45** [clabe45/vidar#55]
Currently, `val()` (found in **util.ts**) accepts a `time` argument, the current time of the movie relative to the provided vidar element. This is redundant, since every vidar element implements a `currentTime` property. We need to remove this argument of `val` and replace its usages with `element.currentTime`.

**Relevant Code**:
- [`vd.val()`](https://github.com/clabe45/vidar/blob/master/src/util.ts#L175)

**Comment by hmansh** [comment]
is this supposed to be changed in the util.ts or in any other files too? I'm new to contributing

**Comment by clabe45** [comment]
Hey, thanks for reaching out!

It should be changed in util.ts, and every call to `val` if you can. Please let me know if you have any other questions!

**Comment by hmansh** [comment]
@clabe45 hey not sure but, if you remove the Params of "time" from val  and replace the occurences of time by element.movie.currentTime then in evaluate function it's throwing errors because it's undefined in some test cases.

**Comment by clabe45** [comment]
It's element.currentTime, not element.movie.currentTime. The first gets the time relative to the element if it's a layer, which might be the same as the movie's time.

In a lot of tests, I did a pretty hacky mock of the layers and movies, by just creating an object with a subset of their properties. Eventually, we should probably replace these with real mocks using our testing framework, but for now adding the currentTime property directly to the mocks should make the tests succeed.

**Comment by hmansh** [comment]
can you assign the issue to me? for the time being, working on it.

**Comment by clabe45** [comment]
awesome, assigning to you now!
