### ISSUE TITLE
Missing Declaration File

### ISSUE THREAD

**Issue by Deravadom** [clabe45/vidar#59]
I'm 99.999% sure it's an issue on my end, but I'm getting this error:
```Could not find a declaration file for modular vidar. '<my path>/node_modules/vidar/dist/vidar-cjs.js` implicitly has 'any' type.```

Oddly, the `dist` folder on my end is missing all the `.d.ts` files that I can see in the repo.
For installation, all I did was `npm i --save-dev vidar`. As far as I can tell, there's no `@types/vidar`.

Any suggestions?

**Comment by Deravadom** [comment]
On further digging, it looks like it could be because there has not been a release since the TS migration

**Comment by clabe45** [comment]
Yes, I just released, try it now.
