### ISSUE TITLE
Pass record type option to MediaRecorder

### ISSUE THREAD

**Issue by clabe45** [clabe45/vidar#95]
`Movie#record` can be called with a `type` option to specify the MIME type of the output video. Right now, it is only being used to construct the output blob, but it also needs to be passed to the [MediaRecorder `mimeType` option](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/MediaRecorder).

**Comment by hmansh** [comment]
Hey is the issue resolved?

**Comment by clabe45** [comment]
No it's not. Feel free to work on this if you want.

**Comment by hmansh** [comment]
@clabe45 what are you currently sending inside the MediaRecorder() as options?

**Comment by clabe45** [comment]
The MediaRecorder object is created [here](https://github.com/clabe45/vidar/blob/master/src/movie.ts#L288). The first argument stream will contain the video and audio data for the recorded blob. The second argument is where we need to add the mimeType argument.

Also, we haven't come up with a good way to make sure the recorded video blob is correct in the unit tests for this method, usually it's just making sure the blob is not empty. This isn't ideal, so if you can think of a better way feel free to use it.
